### ISSUE TITLE
Pipe | breaks table output of values.yml

### ISSUE THREAD

**Issue by p-bogdan** [bitnami/readme-generator-for-helm#116]
I have a following in values.yml -
```yaml
livenessProbe:
  exec:
    command:
      - /bin/sh
      - -c
      - "[ $(find /tmp/health -mmin -0.09 | wc -l) -eq 1 ]"
```
When I run the following command - `readme-generator -v values.yaml -r README.md`
Table renders with the following output - 
![bug_readme-generator](https://github.com/user-attachments/assets/66fbc3df-72d3-442d-8aaa-7f45d3fb4fc2)

So in README.md I had to manually add the escape symbol - `\|` to get the correct table.

I'm just wondering if you have any plans to fix it.
