### ISSUE TITLE
modifier in array throws an error: ERROR: Metadata provided for non existing key

### ISSUE THREAD

**Issue by volker-raschek** [bitnami/readme-generator-for-helm#135]
Hi, 
the following notation throws an error like
```bash
ERROR: Metadata provided for non existing key: documentation.urls[0].description
ERROR: Metadata provided for non existing key: documentation.urls[0].url
```

```yaml
## @param documentation.urls[0].description [string, nullable] Description of the URL.
## @param documentation.urls[0].url [string] URL to further documentation.
documentation:
  urls:
  - description: "Link to google.com"
    url: https://google.com
```

Here is an example to reproduce the error:

```bash
mkdir /tmp/demo
cat > /tmp/demo/package.json <<'EOF'
{
  "name": "demo",
  "license": "MIT",
  "private": true,
  "engineStrict": true,
  "engines": {
    "node": ">=16.0.0",
    "npm": ">=8.0.0"
  },
  "scripts": {
    "readme:parameters": "readme-generator -v values.yaml -r README.md"
  },
  "devDependencies": {
    "@bitnami/readme-generator-for-helm": "^2.7.0"
  }
}
EOF

cat > /tmp/demo/values.yaml <<EOF
## @param documentation.urls[0].description [string, nullable] Description of the URL.
## @param documentation.urls[0].url [string] URL to further documentation.
documentation:
  urls:
  - description: "Link to google.com"
    url: https://google.com
EOF

cat > /tmp/demo/README.md <<EOF
## Parameters
EOF

cd /tmp/demo
npm install
npm run readme:parameters
```

Please adapt the package to support modifiers in arrays.
