### ISSUE TITLE
Optional parameter

### ISSUE THREAD

**Issue by datopsbh** [bitnami/readme-generator-for-helm#138]
Hi,
I developed a generic Helm chart for my company.
I have many parameters for the advanced scenario.
For example:
```yaml
@param initContainers[0].name
@param initContainers[0].image
@param initContainers[0].command
@param initContainers[0].args
initContainers:
- name: echo-container
  image: busybox
  command: ['/bin/sh']
  args: ['-c', 'echo', 'example' ]
```
I don't want to release the values.yaml like this by default.
For example, I would like to release under comments, to show the array should look

```yaml
@optional initContainers[0].name
@optional initContainers[0].image
@optional initContainers[0].command
@optional initContainers[0].args
initContainers:
## - name: echo-container
##  image: busybox
##  command: ['/bin/sh']
##  args: ['-c', 'echo', 'example' ]
```
And show it in README.md
