### ISSUE TITLE
nullable does not allow null as a value

### ISSUE THREAD

**Issue by chasain** [bitnami/readme-generator-for-helm#39]
Using a paramater like:
```yaml
config:
  site:
    ## @param config.site.version [string,nullable] Version of config archive
    ##
    version: null
```
gives a schema definition of:
```json
  "version": {
      "type": "string",
      "description": "Only valid with source: Nexus. Version of config archive",
      "default": "null",
      "nullable": true
  },
```
which doesn't allow for actual null values.
```
config.site.version: Invalid type. Expected: string, given: null
```
if I manually change the schema to:
```json
  "version": {
      "type": ["string", "null"],
      "description": "Only valid with source: Nexus. Version of config archive",
      "default": "null",
      "nullable": true
  },
```
then it seems to work correctly
