### ISSUE TITLE
Nested complex key values are rendered as the entire parent object when parent key == child key prefix

### ISSUE THREAD

**Issue by ericsnv** [bitnami/readme-generator-for-helm#70]
This gets rendered properly:
```yaml
## @param annotations.vault.hashicorp.com/agent-inject Some desc
annotations:
  vault.hashicorp.com/agent-inject: "true"
```

| Name                                                           | Description                         | Value                                                                                                                                          |
| -------------------------------------------------------------- | ----------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------- |
| `annotations.vault.hashicorp.com/agent-inject`                 | Some desc | `true`                                                                                                                                         |

This does not:
```yaml
## @param vault.annotations.vault.hashicorp.com/agent-inject Some desc
vault:
  annotations:
    vault.hashicorp.com/agent-inject: "true"
```

| Name                                                           | Description                         | Value                                                                                                                                          |
| -------------------------------------------------------------- | ----------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------- |
| `vault.annotations.vault.hashicorp.com/agent-inject`                 | Some desc | `{"vault.hashicorp.com/agent-inject":"true"}`                                                                                                                                   |

Notice that the top-level key is the same as the leaf key's prefix (`vault`).

The error is likely in [this function](https://github.com/bitnami-labs/readme-generator-for-helm/blob/f9eb5fd9d35c8d50182123096c098a4185b09955/lib/utils.js#L44)
