### ISSUE TITLE
Skip with Schema Generation

### ISSUE THREAD

**Issue by jl-beast** [bitnami/readme-generator-for-helm#73]
For some Params, I want to skip with Schema Generation as I use this with KubeApps. I want to only show values in the values.schema.json that are useful or desirable to have be set by customers, while still providing documentation. 

The goal is to have people be able to easily spin up an easy chart that only shows values that are important and let the configuration done for more rare things be conducted inside a direct yaml editor.

**Comment by kuisathaverat** [comment]
We have a similar use case. When we configure the helm values, we set the default values, and the rest are marked as `@skip` because they are nullable. In the following example, `stack.mode` is not added to the schema, but it is to the documentation. This makes the schema incomplete to use it in VSCode `# yaml-language-server: $schema=./docs/schema.json`

```yaml
## @section stack Configuration for the deployment
## @param stack.mode [string, nullable] way to deploy
## @param stack.version version of the stack
stack:
  version: 8.10.3
``` 

```markdown
## Parameters

### stack Configuration for the deployment

| Name            | Description          | Value       |
| --------------- | -------------------- | ----------- |
| `stack.mode`    | way to deploy        | `undefined` |
| `stack.version` | version of the stack | `8.10.3`    |
```

```json
{
    "title": "Chart Values",
    "type": "object",
    "properties": {
        "stack": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string",
                    "description": "version of the stack",
                    "default": "8.10.3"
                }
            }
        }
    }
}
```

**Comment by fmulero** [comment]
Hi @jl-beast and @kuisathaverat.

We have released version 2.6.0 and now modifiers also apply to schema generation. Could you please give it a try to check if your issues are solved with that version?

**Comment by kuisathaverat** [comment]
I have to review it with the real YAML I have because some of the default values disappeared with the new version. With a tiny example seems to work fine.

```yaml
## @section stack Configuration for the deployment
## @param stack.mode [string, nullable] way to deploy
## @param stack.version version of the stack
## @param stack.elasticsearch.image image to use for elasticsearch
stack:
  version: 8.10.3
  elasticsearch:
    image: docked.example.com/elasticsearch:8.10.3
```

```json
{
    "title": "Chart Values",
    "type": "object",
    "properties": {
        "stack": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string",
                    "description": "version of the stack",
                    "default": "8.10.3"
                },
                "elasticsearch": {
                    "type": "object",
                    "properties": {
                        "image": {
                            "type": "string",
                            "description": "image to use for elasticsearch",
                            "default": "docked.example.com/elasticsearch:8.10.3"
                        }
                    }
                }
            }
        }
    }
}
```

```markdown
# Cluster Configuration

## Parameters

### stack Configuration for the deployment

| Name                        | Description                    | Value                                     |
| --------------------------- | ------------------------------ | ----------------------------------------- |
| `stack.mode`                | way to deploy                  | `undefined`                               |
| `stack.version`             | version of the stack           | `8.10.3`                                  |
| `stack.elasticsearch.image` | image to use for elasticsearch | `docked.example.com/elasticsearch:8.10.3` |

```
